version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=fudydb-test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"